### ISSUE TITLE
Invalid URI on a valid URI

### ISSUE THREAD

**Issue by michaelryu** [openfoodfacts/openfoodfacts-ruby#19]
When i try `product = Openfoodfacts::Product.get("#{data}", locale: 'world')` in console it works fine but when I put it in my rails app I get

    URI::InvalidURIError (bad URI(is not URI?): http://world.openfoodfacts.org/api/v0/produit/00578561
    .json):

**Comment by stephanegigandet** [comment]
the URI should be http://world.openfoodfacts.org/api/v0/product/00578561.json  (product instead of produit)

**Comment by michaelryu** [comment]
Unfortunately that's the URI the ruby gem creates

**Comment by michaelryu** [comment]
The url works in console and the browser but I think the bigger problem is the octal numbers. 

00578561

will throw off ruby even if i change it to string first

**Comment by nicolasleger** [comment]
@michaelryu Hi, thanks for reporting, can you provide more context please?

Seems to work here :

```
data = '00578561'
Openfoodfacts::Product.url(data, locale: 'world')
# => "http://world.openfoodfacts.org/api/v0/produit/00578561.json"
product = Openfoodfacts::Product.get("#{data}", locale: 'world').to_json
# Working

Openfoodfacts::VERSION
# => "0.3.0"

data = 00578561
# SyntaxError: (irb):14: Invalid octal digit
```

**Comment by nicolasleger** [comment]
@michaelryu Any update or info ?

**Comment by nicolasleger** [comment]
@michaelryu Any update or info ? I will close this issue if not.
