### ISSUE TITLE
Adding Open Beauty Facts as a supported backend

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ruby#21]
Open Beauty uses the same API.

Additionally, there is openfoodfacts.net for experiments and API tests.
allowing to script to read and write from those two would broaden its scope and allow for more experiments.

**Comment by nicolasleger** [comment]
Indeed 👍 , now done in a different wrapper :
- https://github.com/nicolasleger/openbeautyfacts-ruby
- https://rubygems.org/gems/openbeautyfacts
