### ISSUE TITLE
Problems with localised date formats in Press.rb

### ISSUE THREAD

**Issue by epileptic-fish** [openfoodfacts/openfoodfacts-ruby#27]
In Press.rb there are the following localised date formats, used for parsing the dates in the html response from the press page. 

```ruby
LOCALE_DATE_FORMATS = {
    'fr' => '%d/%m/%Y',
    'uk' => '%m/%d/%Y',
    'us' => '%m/%d/%Y',
    'world' => '%m/%d/%Y'
}
```

One issue is with the UK format. This should be the same as the French - day/month/year.

The other issue is that the US format string is correct for US dates but the Press page itself does not appear to use localised dates. All dates are returned in the day/month/year format.

As a result of this, we get the following error when trying to retrieve Press items with locale other than 'fr':

```
irb(main):010:0> press_items = Openfoodfacts::Press.items(locale: 'us')
ArgumentError: invalid date
	from /usr/local/lib/ruby/gems/2.3.0/gems/openfoodfacts-0.3.1/lib/openfoodfacts/press.rb:42:in `strptime'
	from /usr/local/lib/ruby/gems/2.3.0/gems/openfoodfacts-0.3.1/lib/openfoodfacts/press.rb:42:in `block in items'
	from /usr/local/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.4.1/lib/nokogiri/xml/node_set.rb:237:in `block in each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.4.1/lib/nokogiri/xml/node_set.rb:236:in `upto'
	from /usr/local/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.4.1/lib/nokogiri/xml/node_set.rb:236:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/openfoodfacts-0.3.1/lib/openfoodfacts/press.rb:31:in `each_with_index'
	from /usr/local/lib/ruby/gems/2.3.0/gems/openfoodfacts-0.3.1/lib/openfoodfacts/press.rb:31:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/openfoodfacts-0.3.1/lib/openfoodfacts/press.rb:31:in `map'
	from /usr/local/lib/ruby/gems/2.3.0/gems/openfoodfacts-0.3.1/lib/openfoodfacts/press.rb:31:in `items'
	from (irb):10
	from /usr/local/bin/irb:11:in `<main>'
```

**Comment by nicolasleger** [comment]
You're absolutely right! Thanks for reporting
Would you wanna make a PR or should I take care of this?

**Comment by epileptic-fish** [comment]
I have a simple one that I can push up now for you to review! Thanks!

**Comment by nicolasleger** [comment]
Yes, go ahead 👍

**Comment by epileptic-fish** [comment]
Here's the PR @nicolasleger! https://github.com/openfoodfacts/openfoodfacts-ruby/pull/28

Let me know if there are any changes needed!

**Comment by nicolasleger** [comment]
Good, I wanna fix the call on `openfoodfacts.net` with Auth basic to push a new version.
