### ISSUE TITLE
Get categories

### ISSUE THREAD

**Issue by sebfie** [openfoodfacts/openfoodfacts-ruby#7]
How to find REST entry points to add method to this library for example get categories... I will be able to make a pull request.

**Comment by nicolasleger** [comment]
@Ditchou I wish to enhance the library too but the API and REST points are still in design on the OpenFoodFacts side, see the [API wiki page](http://en.wiki.openfoodfacts.org/Project:API). You can join the OFF Slack room #API to get involved in the project (backend written in Perl).

Currently, the only way is to implement new features is to do some ugly web scrapping.
I already did that to [get locales](https://github.com/openfoodfacts/openfoodfacts-ruby/blob/master/lib/openfoodfacts.rb#L21).

**Comment by nicolasleger** [comment]
Added (world) categories fetching and products in `Openfoodfacts::ProductState`.
