### ISSUE TITLE
Fix code scanning alert - Don't use assignment in conditions.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ruby#80]
Tracking issue for:
- [x] https://github.com/openfoodfacts/openfoodfacts-ruby/security/code-scanning/390

**Comment by nicolasleger** [comment]
fixed by https://github.com/openfoodfacts/openfoodfacts-ruby/commit/caea058a3fd7c4a1206763912237439013cc3a04
